/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import controller.ClientController;
import emotionstogether.User;
import javax.swing.JOptionPane;



/**
 *
 * @author Aleksandra
 */
public class LogInForma extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    public LogInForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insert_lbl = new javax.swing.JLabel();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        username_txt_fld = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        password_txt_fld = new javax.swing.JPasswordField();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(800, 300));

        insert_lbl.setText("Unesite korisnicko ime i sifru:");

        username_lbl.setText("Korisnicko ime");

        password_lbl.setText("Sifra");

        username_txt_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txt_fldActionPerformed(evt);
            }
        });

        login_btn.setText("Uloguj se");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        back_btn.setText("Nazad");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_lbl)
                            .addComponent(password_lbl))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_txt_fld, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(password_txt_fld)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(login_btn)
                                .addGap(14, 14, 14))
                            .addComponent(insert_lbl))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(insert_lbl)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_lbl)
                    .addComponent(username_txt_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_lbl)
                    .addComponent(password_txt_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_btn)
                    .addComponent(back_btn))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_txt_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txt_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txt_fldActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        try{
        if(username_txt_fld.getText().isEmpty() || String.valueOf(password_txt_fld.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(this, "Korisnicko ime i lozinka moraju biti popunjeni");
            return;
        }
        User u = new User();
        u.setUsername(username_txt_fld.getText());
        u.setPassword(new String(password_txt_fld.getPassword()));
        
        User korisnik = ClientController.getInstance().login(u);
        
        JOptionPane.showMessageDialog(this, "Uspešno ste se prijavili na sistem");
        
        sesija.Session.getInstance().setUlogovani(korisnik);
        System.out.println("I ovaj deo je uspesno zavrsen u login formi");
        
        
        //prikazi formu koja treba sledeca da se otvori
        MeniAplikacije ma = new MeniAplikacije();
        ma.setVisible(true);
        this.dispose();
        
        }
        catch(Exception e){
           
            e.printStackTrace(); 
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PocetnaFormaKlijent p = new PocetnaFormaKlijent();
        p.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel insert_lbl;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_txt_fld;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_txt_fld;
    // End of variables declaration//GEN-END:variables
}
