/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import controller.ClientController;
import emotionstogether.User;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandra
 */
public class MojProfilForma extends javax.swing.JFrame {

    /**
     * Creates new form MojProfilForma
     */
    
    
    public MojProfilForma() {
        initComponents();
    }
    
     User user = sesija.Session.getInstance().getUlogovani();
         
     String username = user.getUsername();
     String password = user.getPassword();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        podaci_lbl = new javax.swing.JLabel();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        username_txt_fld = new javax.swing.JTextField();
        password_txt_fld = new javax.swing.JTextField();
        change_data_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        podaci_lbl.setText("Podaci Vaseg profila:");

        username_lbl.setText("Korisnicko ime:");

        password_lbl.setText("Lozinka:");

        username_txt_fld.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        username_txt_fld.setEnabled(false);

        password_txt_fld.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        password_txt_fld.setEnabled(false);
        password_txt_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_txt_fldActionPerformed(evt);
            }
        });

        change_data_btn.setText("Promeni podatke");
        change_data_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_data_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Sacuvaj izmene");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        back_btn.setText("Nazad");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(255, 204, 204));
        delete_btn.setText("Obrisi profil");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(username_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_txt_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(podaci_lbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password_txt_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(back_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(change_data_btn)
                        .addGap(18, 18, 18)
                        .addComponent(save_btn)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(podaci_lbl)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_lbl)
                    .addComponent(username_txt_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_lbl)
                    .addComponent(password_txt_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn)
                    .addComponent(change_data_btn)
                    .addComponent(save_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(delete_btn)
                .addGap(19, 19, 19))
        );

        username_txt_fld.setText(username);
        password_txt_fld.setText(password);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_txt_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txt_fldActionPerformed
        try {
            // TODO add your handling code here:
           
        } catch (Exception ex) {
            Logger.getLogger(MojProfilForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_password_txt_fldActionPerformed

    private void change_data_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_data_btnActionPerformed
        // TODO add your handling code here:
        username_txt_fld.enable(true);
        username_txt_fld.setBackground(Color.WHITE);
        password_txt_fld.enable(true);
        password_txt_fld.setBackground(Color.WHITE);
        
        
    }//GEN-LAST:event_change_data_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        User u = sesija.Session.getInstance().getUlogovani();
        
        String noviUsername = username_txt_fld.getText();
        String noviPassword = password_txt_fld.getText();
        u.setNoviUsername(noviUsername);
        u.setNoviPassword(noviPassword);
        
        try {
            ClientController.getInstance().updateUser(u);
            JOptionPane.showMessageDialog(this, "Uspesno ste izmenili podatke");
            this.dispose();
        } catch (Exception ex) {
            System.out.println("Greska iz updateUser dela u moj profil formi: " + ex);
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MeniAplikacije meni = new MeniAplikacije();
        meni.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete svoj profil?", null, JOptionPane.YES_NO_OPTION);
        if(odgovor==0){
            System.out.println("Izabrali ste brisanje");
            User u = sesija.Session.getInstance().getUlogovani();
            try {
                ClientController.getInstance().deleteUser(u);
                JOptionPane.showMessageDialog(this, "Uspesno ste obrisali profil");
                this.dispose();
            } catch (Exception ex) {
                System.err.println("Greska prilikom brisanja korisnika iz forme moj profil: " + ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_delete_btnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton change_data_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JTextField password_txt_fld;
    private javax.swing.JLabel podaci_lbl;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_txt_fld;
    // End of variables declaration//GEN-END:variables

   
    
}

    
